os: linux
language: c
env: 
    - BRANCH="master"
    - BRANCH="develop"
before_install: sudo apt-get update
install: sudo apt-get install -qq libfuse-dev pkg-config fuse
script:
    - cd src/fuse
    - make
after_success:
    - cd src/fuse
    - mkdir test
    - mkdir test_mnt
    - ./qosfs test test_mnt -f -s

